pharmacy/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings 
from django.conf.urls.static import static 
from django.conf.urls import include

from product import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index),
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('report/index/', views.report_index, name='report_index'),

    path('organization/index/', views.organization_index, name='organization_index'),
    path('organization/create/', views.organization_create, name='organization_create'),
    path('organization/edit/<int:id>/', views.organization_edit, name='organization_edit'),
    path('organization/delete/<int:id>/', views.organization_delete, name='organization_delete'),
    path('organization/read/<int:id>/', views.organization_read, name='organization_read'),

    path('invoice/index/', views.invoice_index, name='invoice_index'),
    path('invoice/create/', views.invoice_create, name='invoice_create'),
    path('invoice/edit/<int:id>/', views.invoice_edit, name='invoice_edit'),
    path('invoice/delete/<int:id>/', views.invoice_delete, name='invoice_delete'),
    path('invoice/read/<int:id>/', views.invoice_read, name='invoice_read'),

    path('category/index/', views.category_index, name='category_index'),
    path('category/create/', views.category_create, name='category_create'),
    path('category/edit/<int:id>/', views.category_edit, name='category_edit'),
    path('category/delete/<int:id>/', views.category_delete, name='category_delete'),
    path('category/read/<int:id>/', views.category_read, name='category_read'),

    path('catalog/index/<int:invoice_id>/', views.catalog_index, name='catalog_index'),
    path('catalog/list/', views.catalog_list, name='catalog_list'),
    path('catalog/create/<int:invoice_id>/', views.catalog_create, name='catalog_create'),
    path('catalog/edit/<int:id>/<int:invoice_id>/', views.catalog_edit, name='catalog_edit'),
    path('catalog/delete/<int:id>/<int:invoice_id>/', views.catalog_delete, name='catalog_delete'),
    path('catalog/read/<int:id>/<int:invoice_id>/', views.catalog_read, name='catalog_read'),
    path('catalog/details/<int:id>/', views.catalog_details, name='catalog_details'),    
    path('catalog/basket/', views.basket, name='basket'),
    path('catalog/buy/', views.buy, name='buy'),
    
    path('basket/delete/<int:id>/', views.basket_delete, name='basket_delete'),
    
    path('delivery/list/', views.delivery_list, name='delivery_list'),
    path('delivery/index/<int:id>/', views.delivery_index, name='delivery_index'),
    path('delivery/create/<int:sale_id>/', views.delivery_create, name='delivery_create'),
    path('delivery/edit/<int:id>/', views.delivery_edit, name='delivery_edit'),
    path('delivery/delete/<int:id>/', views.delivery_delete, name='delivery_delete'),
    path('delivery/read/<int:id>/', views.delivery_read, name='delivery_read'),

    path('review/index/', views.review_index, name='review_index'),
    #path('review/list/', views.review_list, name='review_list'),
    #path('review/create/<int:catalog_id>/', views.review_create, name='review_create'),
    path('review/edit/<int:id>/', views.review_edit, name='review_edit'),
    #path('review/delete/<int:id>/', views.review_delete, name='review_delete'),
    
    path('question/index/', views.question_index, name='question_index'),
    path('question/list/', views.question_list, name='question_list'),
    path('question/create/<int:catalog_id>/', views.question_create, name='question_create'),
    path('question/edit/<int:id>/', views.question_edit, name='question_edit'),
    path('question/delete/<int:id>/', views.question_delete, name='question_delete'),
    path('question/read/<int:id>/', views.question_read, name='question_read'),

    path('news/index/', views.news_index, name='news_index'),
    path('news/list/', views.news_list, name='news_list'),
    path('news/create/', views.news_create, name='news_create'),
    path('news/edit/<int:id>/', views.news_edit, name='news_edit'),
    path('news/delete/<int:id>/', views.news_delete, name='news_delete'),
    path('news/read/<int:id>/', views.news_read, name='news_read'),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('logout/', views.logoutUser, name="logout"),
    path('settings/account/', views.UserUpdateView.as_view(), name='my_account'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
#from django.utils.translation import ugettext as _
from django.utils.translation import gettext_lazy as _
from PIL import Image
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
import datetime
from dateutil.relativedelta import relativedelta
from django.utils import timezone
from django import forms

from django.contrib.auth.models import User

# Модели отображают информацию о данных, с которыми вы работаете.
# Они содержат поля и поведение ваших данных.
# Обычно одна модель представляет одну таблицу в базе данных.
# Каждая модель это класс унаследованный от django.db.models.Model.
# Атрибут модели представляет поле в базе данных.
# Django предоставляет автоматически созданное API для доступа к данным

# choices (список выбора). Итератор (например, список или кортеж) 2-х элементных кортежей,
# определяющих варианты значений для поля.
# При определении, виджет формы использует select вместо стандартного текстового поля
# и ограничит значение поля указанными значениями.

# Читабельное имя поля (метка, label). Каждое поле, кроме ForeignKey, ManyToManyField и OneToOneField,
# первым аргументом принимает необязательное читабельное название.
# Если оно не указано, Django самостоятельно создаст его, используя название поля, заменяя подчеркивание на пробел.
# null - Если True, Django сохранит пустое значение как NULL в базе данных. По умолчанию - False.
# blank - Если True, поле не обязательно и может быть пустым. По умолчанию - False.
# Это не то же что и null. null относится к базе данных, blank - к проверке данных.
# Если поле содержит blank=True, форма позволит передать пустое значение.
# При blank=False - поле обязательно.

# Организации 
class Organization(models.Model):
    organization_title = models.CharField(_('organization_title'), max_length=256)
    address = models.CharField(_('address'), max_length=128)
    phone = models.CharField(_('phone'), max_length=128)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'organization'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['organization_title']),            
        ]
        # Сортировка по умолчанию
        ordering = ['organization_title']
    def __str__(self):
        # Вывод названия в тег SELECT 
        return "{}".format(self.organization_title)
        # Override the save method of the model

# Приходные накладные 
class Invoice(models.Model):
    organization = models.ForeignKey(Organization, related_name='invoice_organization', on_delete=models.CASCADE)
    datei = models.DateTimeField(_('datei'))
    numb = models.IntegerField(_('numb'))     
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'invoice'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['datei']),            
        ]
        # Сортировка по умолчанию
        ordering = ['datei']
    def __str__(self):
        # Вывод названия в тег SELECT 
        return "{}".format(self.organization)
        # Override the save method of the model

# Категория товара (услуги)
class Category(models.Model):
    category_title = models.CharField(_('category_title'), max_length=128, unique=True)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'category'
    def __str__(self):
        # Вывод названияв тег SELECT 
        return "{}".format(self.category_title)

# Каталог товаров (услуг)
class Catalog(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='catalog_invoice', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='catalog_category', on_delete=models.CASCADE)
    catalog_title = models.CharField(_('catalog_title'), max_length=255)
    details = models.TextField(_('catalog_details'), blank=True, null=True)
    price = models.DecimalField(_('catalog_price'), max_digits=9, decimal_places=2)
    quantity = models.IntegerField(_('quantity'))
    unit = models.CharField(_('unit'), max_length=32)
    photo = models.ImageField(_('catalog_photo'), upload_to='images/', blank=True, null=True)    
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'catalog'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['catalog_title']),
        ]
        # Сортировка по умолчанию
        ordering = ['catalog_title']
    def __str__(self):
        # Вывод в тег SELECT 
        return "{} {} {}".format(self.category, self.catalog_title, self.price)

# Представление базы данных Каталог товаров (со средней оценкой)
class ViewCatalog(models.Model):
    invoice_id = models.IntegerField(_('invoice_id'))
    category_id = models.IntegerField(_('category_id'))
    category = models.CharField(_('category_title'), max_length=128)
    catalog_title = models.CharField(_('catalog_title'), max_length=255)
    details = models.TextField(_('catalog_details'), blank=True, null=True)
    price = models.DecimalField(_('price'), max_digits=9, decimal_places=2)
    quantity = models.IntegerField(_('quantity'))
    unit = models.CharField(_('unit'), max_length=32)
    photo = models.ImageField(_('catalog_photo'), upload_to='images/', blank=True, null=True)    
    total = models.DecimalField(_('total'), max_digits=9, decimal_places=2, blank=True, null=True)
    sale_quantity = models.IntegerField(_('sale_quantity'))
    available = models.IntegerField(_('available'))
    avg_rating = models.DecimalField(_('avg_rating'), max_digits=6, decimal_places=2)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'view_catalog'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['category']),
            models.Index(fields=['catalog_title']),
        ]
        # Сортировка по умолчанию
        ordering = ['category', 'catalog_title']
        # Таблицу не надо не добавлять не удалять
        managed = False

# Корзина 
class Basket(models.Model):
    basketday = models.DateTimeField(_('basketday'), auto_now_add=True)
    catalog = models.ForeignKey(Catalog, related_name='basket_catalog', on_delete=models.CASCADE)
    price = models.DecimalField(_('price'), max_digits=9, decimal_places=2)
    quantity = models.IntegerField(_('quantity'), default=1)
    user = models.ForeignKey(User, related_name='user_basket', on_delete=models.CASCADE)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'basket'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['basketday']),
        ]
        # Сортировка по умолчанию
        ordering = ['basketday']
    # Сумма по товару
    def total(self):
        return self.price * self.quantity

# Продажа 
class Sale(models.Model):
    saleday = models.DateTimeField(_('saleday'), auto_now_add=True)
    catalog = models.ForeignKey(Catalog, related_name='sale_catalog', on_delete=models.CASCADE)
    price = models.DecimalField(_('price'), max_digits=9, decimal_places=2)
    quantity = models.IntegerField(_('quantity'), default=1)
    user = models.ForeignKey(User, related_name='sale_user', on_delete=models.CASCADE)
    address = models.CharField(_('delivery_address'), max_length=128, blank=True, null=True)
    rating = models.IntegerField(_('rating'), blank=True, null=True)
    details = models.TextField(_('review_details'), blank=True, null=True)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'sale'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['saleday']),
        ]
        # Сортировка по умолчанию
        ordering = ['saleday']
    # Сумма по товару
    def total(self):
        return self.price * self.quantity
    def __str__(self):
        # Вывод в тег SELECT 
        return "{} {} {}".format(self.saleday, self.catalog, self.user.username)
        # Таблицу не надо не добавлять не удалять
        #managed = False
    def save(self):
        if self.id == None:
            super().save()
            print( str(self.id) )
            print( str(self.saleday) )
            delivery = Delivery()
            delivery.sale_id = self.id
            delivery.deliveryday = self.saleday
            delivery.movement = _('Application accepted for processing')
            delivery.details= _('Application accepted for processing')
            delivery.save()
            delivery.deliveryday = self.saleday
            delivery.save()
        else:
            super().save()

# Представление базы данных Продажа (с последним движением по доставке)
class ViewSale(models.Model):
    username = models.CharField(_('username'), max_length=128)
    first_name = models.CharField(_('first_name'), max_length=128)
    last_name = models.CharField(_('last_name'), max_length=128)
    saleday = models.DateTimeField(_('saleday'))
    catalog_id = models.IntegerField(_('catalog_id'))
    category = models.CharField(_('category'), max_length=128)
    catalog_title = models.CharField(_('catalog_title'), max_length=255)        
    price = models.DecimalField(_('price'), max_digits=9, decimal_places=2)
    photo = models.ImageField(_('photo'), upload_to='images/', blank=True, null=True)
    quantity = models.IntegerField(_('quantity'))
    total = models.DecimalField(_('total'), max_digits=9, decimal_places=2)
    user_id = models.IntegerField(_('user_id'))
    address = models.CharField(_('delivery_address'), max_length=128, blank=True, null=True)
    rating = models.IntegerField(_('rating'), blank=True, null=True)

templates/catalog/basket.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Basket" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "Basket" %}</h2>
{% if basket.count > 0 %}
{% for b in basket %}
<div class="row justify-content-center">
		<div class="card" style="width: 100%">
			<div class="card-header">
				<h5>{{ b.catalog.category }}</h5>
				<h5>{{ b.catalog.subcategory }}</h5>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col-md-2">
						{% if b.catalog.id == 1 %}
							<img class="img-center2" src="{% static 'images/catalog01.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 2 %}
							<img class="img-center2" src="{% static 'images/catalog02.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 3 %}
							<img class="img-center2" src="{% static 'images/catalog03.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 4 %}
							<img class="img-center2" src="{% static 'images/catalog04.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 5 %}
							<img class="img-center2" src="{% static 'images/catalog05.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 6 %}
							<img class="img-center2" src="{% static 'images/catalog06.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 7 %}
							<img class="img-center2" src="{% static 'images/catalog07.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 8 %}
							<img class="img-center2" src="{% static 'images/catalog08.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 9 %}
							<img class="img-center2" src="{% static 'images/catalog09.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 10 %}
							<img class="img-center2" src="{% static 'images/catalog10.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 11 %}
							<img class="img-center2" src="{% static 'images/catalog11.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 12 %}
							<img class="img-center2" src="{% static 'images/catalog12.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 13 %}
							<img class="img-center2" src="{% static 'images/catalog13.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 14 %}
							<img class="img-center2" src="{% static 'images/catalog14.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 15 %}
							<img class="img-center2" src="{% static 'images/catalog15.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 16 %}
							<img class="img-center2" src="{% static 'images/catalog16.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 17 %}
							<img class="img-center2" src="{% static 'images/catalog17.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 18 %}
							<img class="img-center2" src="{% static 'images/catalog18.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 19 %}
							<img class="img-center2" src="{% static 'images/catalog19.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 20 %}
							<img class="img-center2" src="{% static 'images/catalog20.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 21 %}
							<img class="img-center2" src="{% static 'images/catalog21.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 22 %}
							<img class="img-center2" src="{% static 'images/catalog22.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 23 %}
							<img class="img-center2" src="{% static 'images/catalog23.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 24 %}
							<img class="img-center2" src="{% static 'images/catalog24.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 25 %}
							<img class="img-center2" src="{% static 'images/catalog25.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 26 %}
							<img class="img-center2" src="{% static 'images/catalog26.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 27 %}
							<img class="img-center2" src="{% static 'images/catalog27.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 28 %}
							<img class="img-center2" src="{% static 'images/catalog28.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 29 %}
							<img class="img-center2" src="{% static 'images/catalog29.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% elif b.catalog.id == 30 %}
							<img class="img-center2" src="{% static 'images/catalog30.jpg' %}" alt="{{ b.catalog.photo.url }}">
						{% else %}
							{% if b.catalog.photo.url != None %}
								<img class="img-center2" src="{{ b.catalog.photo.url}}" alt="{{ b.catalog.photo.url }}">
							{% endif %}
						{% endif %}
					</div>
					<div class="col-md-8">
						<h5 class="card-title">{{ b.catalog.title }}</h5>
					</div>
					<div class="col-md-2">
						<h6 class="card-title"><strong>{{ b.quantity }}ˣ{{ b.price | stringformat:"1.0f" }}</strong> 〒</h6>
						<form method="post" name="plusminusForm">
							{% csrf_token %}
							<input hidden type="text" name="basket_id" size="0" value="{{ b.id }}">
							<input hidden type="text" name="quantity" size="0" value="{{ b.quantity }}">
							<button type="submit" name="btn_plus" class="btn btn-outline-success">+</button>
							<button type="submit" name="btn_minus" class="btn btn-outline-success">-</button>
						</form>
						<h4 class="card-title"><strong>{{ b.total | stringformat:"1.0f" }}</strong> 〒</h4>
						<a onclick="return confirm('Удалить запись?')" class="btn btn-outline-danger" href="{% url 'basket_delete' b.id %}">{% trans "Delete" %}</a>
					</div>
				</div>
			</div>
			<div class="card-footer text-muted">
				<p><p>
			</div>
		</div>
</div>
{% endfor %}
{% if basket_total > 0 %}
	<div class="row justify-content-center" id="row_go_payment">
		<div class="card" style="width: 100%">
			<div class="card-header text-center" >
				<h3 class="card-title"><strong>{% trans "Basket total" %} - {{ basket_total | stringformat:"1.0f"}}</strong> 〒</h3>
			</div>
			<div class="card-body">
				<div class="row justify-content-center">
					<input id="btn_go_payment" type="button" class="btn btn-outline-primary" value="{% trans "Go payment" %}">
				</div>
			</div>
		</div>
	</div>

	<div class="row justify-content-center" id="div_payment" style="visibility: hidden">
		<form class="form-horizontal" method="post" style="width: 100%" name="paymentForm">
		{% csrf_token %}
		<div class="card" style="width: 100%">
			<div class="card-header text-center" >
				<h3>{% trans "Payment method" %}</h3>
				<h3 class="card-title"><strong>{% trans "Basket total" %} - {{ basket_total }}</strong> 〒</h3>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col-md-6">
						<div class="controls">
							<input type="radio" id="paymentCard" name="paymentMode" value="card" checked>
							<label for="paymentCard">{% trans "Card" %}</label>
						</div>
						<div class="controls">
							<input type="radio" id="paymentCash" name="paymentMode" value="cash" >
							<label for="paymentCash">{% trans "In cash" %}</label>
						</div>
						<hr>
						<label for="id_title">{% trans "delivery_address" %}</label>
						<br>
						<input type="text" name="address" size="50" maxlength="64" required id="id_address" value="{{ address }}">
					</div>
					<div class="col-md-6">
						<div class="card" style="margin:10px;">
							<div class="card-body">
									<img src="{% static "images/card.png" %}" style="width:100%">
									<h5 class="card-title">Не вводите данные реальной карты</h5>
									<div>
										<label for="card-number">{% trans "Card number" %}</label>
										<input type="text" required minlength="4" maxlength="4" onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="card_number_1" name="card_number_1" maxlength="4" size="4" value=""/>
										<input type="text" required minlength="4" maxlength="4" onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="card_number_2" name="card_number_2" maxlength="4" size="4" value=""/>
										<input type="text" required minlength="4" maxlength="4" onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="card_number_3" name="card_number_3" maxlength="4" size="4" value=""/>
										<input type="text" required minlength="4" maxlength="4" onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="card_number_4" name="card_number_4" maxlength="4" size="4" value=""/>
									</div>
									<div>
										<label>{% trans "Card holder" %}</label>
										<input type="text" required id="card_holder" name="card_holder" size="30" value=""/>
									</div>
									<div>
										<label>{% trans "Expiration date" %}</label>
										<input type="text" required minlength="2" maxlength="2" onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="month" name="month" maxlength="2" size="3" placeholder="MM" value=""/>
										<input type="text" required minlength="4" maxlength="4" onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="year" name="year" maxlength="4" size="5" placeholder="YYYY" value=""/>
										<label>CCV</label>
										<input required type="password" minlength="3" maxlength="3" onkeypress='return event.charCode >= 48 && event.charCode <= 57' id="card_ccv" name="card_ccv" maxlength="3" size="3"/>
									</div>

							</div>
						</div>
					</div>
				</div>
				<hr>
				<div class="row justify-content-center">
					<button type="submit" name="buy" class="btn btn-outline-success" style="width:100px" >{% trans "Buy" %}</button>
					<a class="btn btn-outline-info" style="width:100px" href="{% url 'catalog_list' %}">{% trans "Back" %}</a>
				</div>
			</div>
		</div>
		</form>
	</div>
{% endif %}

{% endif %}
<script>
	// Показ способа оплаты
	btn_go_payment.onclick = function() {
		var div = document.getElementById('div_payment');
		div.style.visibility ='visible'
		//console.log("Cпособ оплаты теперь видимый");
		var row = document.getElementById('row_go_payment');
		row.style.visibility ='hidden'
		row.style.height = 0;
		//console.log("Кнопка перехода к выбору способа оплаты сокрыта");
	};
	// Опредление способа оплаты
	var payment_mode = document.paymentForm.paymentMode;
	for (var i = 0; i < payment_mode.length; i++) {
		payment_mode[i].addEventListener('change', function() {
			if(payment_mode[0].checked){
				// При оплате карточкой надо ввести данные карточки
				//console.log("Card");
				document.getElementById('card_number_1').setAttribute("required", "");
				document.getElementById('card_number_2').setAttribute("required", "");
				document.getElementById('card_number_3').setAttribute("required", "");
				document.getElementById('card_number_4').setAttribute("required", "");
				document.getElementById('card_holder').setAttribute("required", "");
				document.getElementById('card_holder').setAttribute("required", "");
				document.getElementById('month').setAttribute("required", "");
				document.getElementById('year').setAttribute("required", "");
				document.getElementById('card_ccv').setAttribute("required", "");
			}
			if(payment_mode[1].checked){
				// При оплате наличными данные карточки не нужны
				//console.log("Cash");
				document.getElementById('card_number_1').removeAttribute("required");
				document.getElementById('card_number_2').removeAttribute("required");
				document.getElementById('card_number_3').removeAttribute("required");
				document.getElementById('card_number_4').removeAttribute("required");
				document.getElementById('card_holder').removeAttribute("required");
				document.getElementById('card_holder').removeAttribute("required");
				document.getElementById('month').removeAttribute("required");
				document.getElementById('year').removeAttribute("required");
				document.getElementById('card_ccv').removeAttribute("required");
			}
		});
	}
</script>
{% endblock content %}